version: '3'
services:   
  mongo:      
    image: mongo:4.4.12      
    ports:         
      - 27017:27017        
  auth:      
    build: ./users
    restart: always  
    ports: 
      - 5000:5000          
    depends_on:           
      - mongo
  forms:
    build: ./forms
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./images:/root/images
    depends_on:           
      - mongo
  gateway:
    build: ./gateway
    restart: always
    ports:
      - 80:4000
  

 